=== pedrodiasparente/PRI2020/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PR (keyName,titulo,subtitulo?,beginDate,endDate,supervisor,workteam,abstract,deliverables) >

<!ELEMENT keyName (#PCDATA) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT subtitulo (#PCDATA) >
<!ELEMENT beginDate (#PCDATA) >
<!ELEMENT endDate (#PCDATA) >

<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
    url CDATA #REQUIRED >
    
<!ELEMENT workteam (worker)+ >
<!ELEMENT worker (nome,email) >
<!ATTLIST worker
    numero ID #REQUIRED
    mailURL CDATA #REQUIRED>

<!ELEMENT nome (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT abstract (paragrafo)+ >

<!ELEMENT paragrafo (texto|bold|italico|sublinhado|externalLink|internalLink)* >

<!ELEMENT texto (#PCDATA) >
<!ELEMENT bold (#PCDATA) >
<!ELEMENT italico (#PCDATA) >
<!ELEMENT sublinhado (#PCDATA) >

<!ELEMENT externalLink (#PCDATA) >
<!ATTLIST externalLink 
    url CDATA #REQUIRED >
<!ELEMENT internalLink (#PCDATA) >
<!ATTLIST internalLink 
    url CDATA #REQUIRED >

<!ELEMENT deliverables (item)+ >
<!ELEMENT item (#PCDATA) >
<!ATTLIST item
    url CDATA #REQUIRED >

=== pedrodiasparente/PRI2020/TP2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "file:/home/pedro/Desktop/PRI/PR.dtd">
<PR>
    <keyName>
        PRI_TP1_ProjectRec
    </keyName>
    <titulo>
        Project Record TP1 PRI
    </titulo>
    <subtitulo>
        Random Subtitle
    </subtitulo>
    <beginDate>
        Outubro 2020
    </beginDate>
    <endDate>
        Outubro 2020
    </endDate>
    <supervisor url="www.di.uminho.pt/~jcr">
        Jos√© Carlos Ramalho
    </supervisor>
    <workteam>
        <worker numero="A85919" mailURL="a85919@alunos.uminho.pt">
            <nome>
                Pedro Dias Parente
            </nome>
            <email>
                a85919@alunos.uminho.pt
            </email>
        </worker>
    </workteam>
    <abstract>
        <paragrafo>
            <texto>Bla bla bla, a seguinte parte vai ser em </texto>
            <bold>BOLD, e agora vai ser </bold>
            <italico>italico tuuuc </italico>
            <texto>:) , agora um pequeno </texto>
            <internalLink url="www.google.pt">
                internal link
            </internalLink>
            <texto> e agora um </texto>
            <externalLink url="www.youtube.com">
                external link mano
            </externalLink>
        </paragrafo>
        <paragrafo>
            <texto>E agora mano, que fazer?</texto>
        </paragrafo>
    </abstract>
    <deliverables>
        <item url="www.facebook.com">
            Report (XML Version)
        </item>
    </deliverables>
</PR>

=== pedrodiasparente/PRI2020/TP3/TP3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "file:/home/pedro/Desktop/PRI/TPCS/TP2/PR.dtd">
<PR>
    <keyName>
        PRI_TP3_ProjectRec
    </keyName>
    <titulo>
        Project Record TP3 PRI
    </titulo>
    <beginDate>
        Outubro 2020
    </beginDate>
    <endDate>
        Outubro 2020
    </endDate>
    <supervisor url="www.di.uminho.pt/~jcr">
        José Carlos Ramalho
    </supervisor>
    <workteam>
        <worker numero="A85919" mailURL="mailto:a85919@alunos.uminho.pt">
            <nome>
                Pedro Dias Parente
            </nome>
            <email>
                a85919@alunos.uminho.pt
            </email>
        </worker>
    </workteam>
    <abstract>
        <paragrafo>
            <texto>
                Para este trabalho, foi contruído pelo aluno um site usando ficheiros xsl que usam ficheiros .xml como input.
            </texto>
        </paragrafo>
        <paragrafo>
            <texto>
                Foi gerado então html de acordo com as especificações do ficheiro .xsl. O aluno decidiu fazer dois sites, um em formato 
            </texto>
            <bold>
                single-page
            </bold>
            <texto> e outro em formato </texto>
            <bold>
                multi-page.
            </bold>
        </paragrafo>
        <paragrafo>
            <texto>
                Foi ainda feito css para o site estar mais "amigável" aos olhos.
            </texto>
        </paragrafo>
    </abstract>
    <deliverables>
        <item ref="arq.xml">
            Ficheiro xml de input
        </item>
        <item ref="arq.dtd">
            Ficheiro dtd que contém a sintaxe do ficheiro xml de input
        </item>
        <item ref="single-page/arq.xsl">
            Ficheiro .xsl do site em formato single-page
        </item>
        <item ref="single-page/arq.html">
            Página .html do site em formato single-page
        </item>
        <item ref="multi-page/arq.xsl">
            Ficheiro .xsl do site em formato multi-page
        </item>
        <item ref="multi-page/arqsite/index.html">
            Página .html do site em formato multi-page
        </item>
    </deliverables>
</PR>

=== pedrodiasparente/PRI2020/TP2/TP2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "file:/home/pedro/Desktop/PRI/TPCS/TP2/PR.dtd">
<PR>
    <keyName>
        PRI_TP1_ProjectRec
    </keyName>
    <titulo>
        Project Record TP1 PRI
    </titulo>
    <subtitulo>
        Random Subtitle
    </subtitulo>
    <beginDate>
        Outubro 2020
    </beginDate>
    <endDate>
        Outubro 2020
    </endDate>
    <supervisor url="www.di.uminho.pt/~jcr">
        José Carlos Ramalho
    </supervisor>
    <workteam>
        <worker numero="A85919" mailURL="mailto:a85919@alunos.uminho.pt">
            <nome>
                Pedro Dias Parente
            </nome>
            <email>
                a85919@alunos.uminho.pt
            </email>
        </worker>
    </workteam>
    <abstract>
        <paragrafo>
            <texto>
                Para este trabalho, foi contruído pelo aluno um ficheiro 
            </texto>
            <bold> dtd </bold>
            <texto>
                que fosse capaz de gerar
            </texto>
            <bold> xml </bold>
            <texto>
                de acordo com as caraterísticas de um 
            </texto>
            <bold>
                Project Record.
            </bold>
        </paragrafo>
        <paragrafo>
            <texto>
                Depois de gerado o xml foi tambem usado o ficheiro gerado para fazer o próprio Project Record.
            </texto>
        </paragrafo>
    </abstract>
    <deliverables>
        <item ref="TP2.html">
            Report (HTML Version)
        </item>
        <item ref="TP2.xml">
            Report (XML Version)
        </item>
    </deliverables>
</PR>
